#!/usr/bin/env python3
"""Generate build.ninja for AS&S Game.

Run:  python3 configure.py        (creates build.ninja)
Then: ninja                       (builds the ROM)
      ninja test                  (builds + runs tests)
      ninja run                   (builds + opens in mGBA)
      ninja -t clean              (removes build artifacts)

Re-run configure.py after adding/removing source files.
"""
import glob, os, sys

# ── Configuration ────────────────────────────────────────────────────
ROM       = "ass_game"
BUILD     = "build"
SRCDIR    = "src"
INCDIR    = "include"
TOOLDIR   = "tools"

ZIG       = os.environ.get("ZIG", "zig")
HOSTCC    = os.environ.get("HOSTCC", "cc")

TARGET    = "-target arm-freestanding-none -mcpu=arm7tdmi -mfloat-abi=soft"
CFLAGS    = f"{TARGET} -mthumb -O2 -Wall -Wextra -Wno-unused-parameter -I{INCDIR} -fno-strict-aliasing"
ASFLAGS   = TARGET
LDFLAGS   = f"{TARGET} -mthumb -T gba_cart.ld -nostartfiles"

# ── Discover sources ─────────────────────────────────────────────────
all_c     = sorted(glob.glob(f"{SRCDIR}/*.c"))
all_s     = sorted(glob.glob(f"{SRCDIR}/*.s"))
all_h     = sorted(glob.glob(f"{INCDIR}/*.h"))

# Game ROM: everything except test_main.c
game_c    = [f for f in all_c if os.path.basename(f) != "test_main.c"]
# Test ROM: everything except main.c
test_c    = [f for f in all_c if os.path.basename(f) != "main.c"]

def obj(src, prefix=""):
    """src/foo.c → build/[prefix]foo.o"""
    base = os.path.splitext(os.path.basename(src))[0]
    return f"{BUILD}/{prefix}{base}.o"

game_objs = [obj(f) for f in game_c] + [obj(f) for f in all_s]
test_objs = [obj(f, "test_") for f in test_c] + [obj(f) for f in all_s]

# Implicit header deps — every .c depends on all headers (conservative but correct).
# Ninja's depfile support (gcc -MD) would be better, but zig cc doesn't emit .d files
# in all configurations.  This is fine for a project this size.
hdeps     = " ".join(all_h)

# ── Write build.ninja ────────────────────────────────────────────────
lines = []
w = lines.append

w(f"# build.ninja — generated by configure.py")
w(f"# Re-run:  python3 configure.py")
w(f"")
w(f"builddir = {BUILD}")
w(f"")

# ── Rules ────────────────────────────────────────────────────────────
w(f"rule cc")
w(f"  command = {ZIG} cc {CFLAGS} -MD -MF $out.d -c $in -o $out")
w(f"  depfile = $out.d")
w(f"  description = CC $in")
w(f"")
w(f"rule as")
w(f"  command = {ZIG} cc {ASFLAGS} -c $in -o $out")
w(f"  description = AS $in")
w(f"")
w(f"rule link")
w(f"  command = {ZIG} cc {LDFLAGS} $in -o $out")
w(f"  description = LINK $out")
w(f"")
w(f"rule elf2bin")
w(f"  command = python3 {TOOLDIR}/elf2bin.py $in $out")
w(f"  description = ELF2BIN $out")
w(f"")
w(f"rule gbafix")
w(f"  command = cp $in $out && $builddir/gbafix $out")
w(f"  description = GBAFIX $out")
w(f"")
w(f"rule hostcc")
w(f"  command = {HOSTCC} -O2 -o $out $in")
w(f"  description = HOSTCC $in")
w(f"")
w(f"rule run_tests")
w(f"  command = python3 {TOOLDIR}/run_tests.py $in")
w(f"  description = TEST $in")
w(f"  pool = console")
w(f"")
w(f"rule run_emu")
w(f"  command = open -a mGBA $in")
w(f"  description = RUN $in")
w(f"  pool = console")
w(f"")

# ── Host tools ───────────────────────────────────────────────────────
w(f"build $builddir/gbafix: hostcc {TOOLDIR}/gbafix.c")
w(f"")

# ── Game ROM objects ─────────────────────────────────────────────────
for src in game_c:
    w(f"build {obj(src)}: cc {src} | {hdeps}")
for src in all_s:
    w(f"build {obj(src)}: as {src}")
w(f"")

# ── Game ROM link + extract ──────────────────────────────────────────
game_obj_str = " ".join(game_objs)
w(f"build $builddir/{ROM}.elf: link {game_obj_str}")
w(f"build {ROM}.raw.gba: elf2bin $builddir/{ROM}.elf")
w(f"build {ROM}.gba: gbafix {ROM}.raw.gba | $builddir/gbafix")
w(f"")

# ── Test ROM objects ─────────────────────────────────────────────────
for src in test_c:
    w(f"build {obj(src, 'test_')}: cc {src} | {hdeps}")
w(f"")

# ── Test ROM link + extract ──────────────────────────────────────────
test_obj_str = " ".join(test_objs)
w(f"build $builddir/{ROM}_test.elf: link {test_obj_str}")
w(f"build {ROM}_test.raw.gba: elf2bin $builddir/{ROM}_test.elf")
w(f"build {ROM}_test.gba: gbafix {ROM}_test.raw.gba | $builddir/gbafix")
w(f"")

# ── Phony targets ────────────────────────────────────────────────────
w(f"build test: run_tests {ROM}_test.gba")
w(f"build run: run_emu {ROM}.gba")
w(f"")
w(f"default {ROM}.gba")
w(f"")

with open("build.ninja", "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"configure: wrote build.ninja ({len(game_c)} game sources, {len(test_c)} test sources, {len(all_s)} asm)")
